services:
  rdbms:
    image: 'postgres:latest'
    container_name: easyshoppingapi
    restart: always
    env_file:
      - .env.docker
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass admin"]
    restart: always

